# TCL File Generated by Component Editor 18.1
# Sun Mar 16 16:18:45 ICT 2025
# DO NOT MODIFY


# 
# convolutionIP "convolutionIP" v1.0
#  2025.03.16.16:18:45
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module convolutionIP
# 
set_module_property DESCRIPTION ""
set_module_property NAME convolutionIP
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME convolutionIP
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL convolutionIP
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file convolutionIP.sv SYSTEM_VERILOG PATH convolutionIP.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL convolutionIP
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file convolutionIP.sv SYSTEM_VERILOG PATH convolutionIP.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock ""
set_interface_property avalon_slave_0 associatedReset ""
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 X0 writebyteenable_n Input 8
add_interface_port avalon_slave_0 X1 writebyteenable_n Input 8
add_interface_port avalon_slave_0 X2 writebyteenable_n Input 8
add_interface_port avalon_slave_0 X3 writebyteenable_n Input 8
add_interface_port avalon_slave_0 X4 writebyteenable_n Input 8
add_interface_port avalon_slave_0 X5 writebyteenable_n Input 8
add_interface_port avalon_slave_0 X6 writebyteenable_n Input 8
add_interface_port avalon_slave_0 X7 writebyteenable_n Input 8
add_interface_port avalon_slave_0 X8 writebyteenable_n Input 8
add_interface_port avalon_slave_0 H0 writebyteenable_n Input 8
add_interface_port avalon_slave_0 H1 writebyteenable_n Input 8
add_interface_port avalon_slave_0 H2 writebyteenable_n Input 8
add_interface_port avalon_slave_0 H3 writebyteenable_n Input 8
add_interface_port avalon_slave_0 H4 writebyteenable_n Input 8
add_interface_port avalon_slave_0 H5 writebyteenable_n Input 8
add_interface_port avalon_slave_0 H6 writebyteenable_n Input 8
add_interface_port avalon_slave_0 H7 writebyteenable_n Input 8
add_interface_port avalon_slave_0 H8 writebyteenable_n Input 8
add_interface_port avalon_slave_0 rst beginbursttransfer Input 1
add_interface_port avalon_slave_0 Y readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1

